name: rlcache
channels:
  - anaconda
dependencies:
 - python
 - pip
 - numpy
 - urllib3
 - jupyter
 - pydot
 - graphviz
 - tensorflow-gpu
 - tensorflow-probability
 - pip:
   - sklearn
   - jupyter_tensorboard
   - rlgraph
   - matplotlib
   - flask
   - gym
