name: rlcache
dependencies:
 - python
 - numpy
 - docopt
 - urllib3
 - jupyter
 - pydot
 - graphviz
 - tensorflow-gpu
 - tensorflow-probability
 - pip:
   - sklearn
   - watermark
   - jupyter_tensorboard
   - rlgraph
   - matplotlib
   - faker
   - flask
   - gym